manifest_version = 2
name = "Integrate Storj using Rust"
description = "Use Storj as a backend origin for service decentralized objects to the fastly Compute@Edge service."
authors = ["<karl@storj.io>"]
language = "rust"

[setup]

  [setup.backends]

    [setup.backends.bucket_origin]
      address = "mock-s3.edgecompute.app"
      port = 443
